import type { Metadata } from "next";
import {
  Source_Serif_4,
  Source_Sans_3,
  Source_Code_Pro,
} from "next/font/google";

import "../components/globalStyle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sourceSerif = Source_Serif_4({
  subsets: ["latin"],
  variable: "--font-serif",
});

const sourceSans = Source_Sans_3({
  subsets: ["latin"],
  variable: "--font-sans",
});

const sourceCode = Source_Code_Pro({
  subsets: ["latin"],
  variable: "--font-code",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="de"
      className={`${sourceSerif.variable} ${sourceSans.variable} ${sourceCode.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
