import type { Metadata } from "next";
import {
  Source_Serif_4,
  Source_Sans_3,
  Source_Code_Pro,
  Inter,
} from "next/font/google";

import "../components/globalStyle";
import { Page } from "@/components/Page";
import { WtalPanorama } from "@samisdat/wtal-panorama";
import { Container } from "@/components/Container";
import "@samisdat/wtal-panorama/style.css";
import { Colophon } from "@/components/Colophon";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sourceSerif = Source_Serif_4({
  subsets: ["latin"],
  variable: "--font-serif",
});

const sourceSans = Source_Sans_3({
  subsets: ["latin"],
  variable: "--font-sans",
});

const sourceCode = Source_Code_Pro({
  subsets: ["latin"],
  variable: "--font-code",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="de"
      className={`${sourceSerif.variable} ${sourceSans.variable} ${sourceCode.variable}`}
    >
      <body>
        <Page>
          <WtalPanorama />
          <Container>
            {children}
            <Colophon />
          </Container>
        </Page>
      </body>
    </html>
  );
}
